version: "3"

services:
  express-app-test-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: express-app-test
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    container_name: express-app-test-container
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/express-app-test
      - /usr/src/express-app-test/node_modules
    networks:
      - node-network
    command: yarn test
    env_file: ./.env.example
