version: "3"

services:
  express-app-prod-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: express-app-prod
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    container_name: express-app-prod-container
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./build:/usr/src/express-app-prod
      - /usr/src/express-app-prod/node_modules
    networks:
      - node-network
    command: yarn run cross-env NODE_ENV=production node src/index.js
    env_file: ./.env
